// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
	export interface GlobalComponents {
		EchartsBarChart: typeof import('./../components/echarts/barChart/index.vue')['default']
		EchartsBarLineChart: typeof import('./../components/echarts/bar-line-chart/index.vue')['default']
		EchartsLineChart: typeof import('./../components/echarts/lineChart/index.vue')['default']
		ListAnimateList: typeof import('./../components/list/animateList/index.vue')['default']
		Menu: typeof import('./../components/menu/index.vue')['default']
		Plate: typeof import('./../components/plate/index.vue')['default']
		PlatePostFloor: typeof import('./../components/plate/post/floor.vue')['default']
		PlatePostTypeA: typeof import('./../components/plate/post/typeA.vue')['default']
		PlatePostTypeB: typeof import('./../components/plate/post/typeB.vue')['default']
		PlatePostTypeC: typeof import('./../components/plate/post/typeC.vue')['default']
	}
}

export {}
