// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
	export interface GlobalComponents {
		ListAnimateList: typeof import('./../components/list/animateList/index.vue')['default']
		Menu: typeof import('./../components/menu/index.vue')['default']
	}
}

export {}
